import { PT_Sans_Caption } from 'next/font/google'
import './index.css'

// components
import Navbar from '@/components/Navbar'

// founctionals
const sans = PT_Sans_Caption({ subsets: ['latin'], weight: ['400','700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Navbar />
        <main className='max-container'>
          {children}
        </main>
      </body>
    </html>
  )
}